### ISSUE TITLE
don't read arbitrary sized blobs into memory

### ISSUE THREAD

**Issue by kapilt** [juju-solutions/jujuresources#1]
https://github.com/juju-solutions/jujuresources/blob/master/jujuresources/backend.py#L92

Glad to see this facility being developed, but some sanity around dealing with large files would be nice.

**Comment by johnsca** [comment]
Good point.  There are a couple of places where I'm reading URLs of arbitrary size, as well.  I've got a fix to chunk or limit things, but I need to fix / update the tests.
